name: Fetch JBZD Memes

on:
  workflow_dispatch:  # ręczne uruchomienie

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run fetch script
        run: python fetch_memes.py

      - name: Commit CSV
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add memes-data/*.csv
          git commit -m "Add latest memes CSV" || echo "No changes to commit"
          git push
